name: feature_core
description: Core classes and contracts for managing features.
version: 1.0.2
repository: https://github.com/nogipx/feature

environment:
  sdk: '>=2.14.2 <3.0.0'

dependencies:
  rxdart: ^0.27.3
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
