name: feature_core
description: A starting point for Dart libraries or applications.
version: 0.1.0

environment:
  sdk: '>=2.14.2 <3.0.0'

dependencies:
  rxdart: ^0.27.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
