name: feature_source_retain
description: Feature source that allows to retain feature state across launches.
version: 1.0.1
repository: https://github.com/nogipx/feature

environment:
  sdk: '>=2.14.2 <3.0.0'

dependencies:
  shared_preferences: ^2.0.15
  feature_core: ^1.0.1
#  feature_core:
#    path: /Users/nogipx/Documents/Projects/nogipx/feature/feature_core

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
